### ISSUE TITLE
Issues installing Bundler

### ISSUE THREAD

**Issue by jcbelair** [BitcoinQnA/Bitcoiner.Guide#21]
**Describe the issue**
trying to install bundler. Mac Os ventura 13.4. I get permission denied

**Which page(s) are the issues found on?**

**Screenshots**

ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/gems/2.6.0 directory.
	/Library/Ruby/Site/2.6.0/rubygems/installer.rb:712:in `verify_gem_home'
	/Library/Ruby/Site/2.6.0/rubygems/installer.rb:902:in `pre_install_checks'
	/Library/Ruby/Site/2.6.0/rubygems/installer.rb:302:in `install'
	/Library/Ruby/Site/2.6.0/rubygems/resolver/specification.rb:104:in `install'
	/Library/Ruby/Site/2.6.0/rubygems/request_set.rb:194:in `block in install'
	/Library/Ruby/Site/2.6.0/rubygems/request_set.rb:182:in `each'
	/Library/Ruby/Site/2.6.0/rubygems/request_set.rb:182:in `install'
	/Library/Ruby/Site/2.6.0/rubygems/commands/install_command.rb:214:in `install_gem'
	/Library/Ruby/Site/2.6.0/rubygems/commands/install_command.rb:230:in `block in install_gems'
	/Library/Ruby/Site/2.6.0/rubygems/commands/install_command.rb:223:in `each'
	/Library/Ruby/Site/2.6.0/rubygems/commands/install_command.rb:223:in `install_gems'
	/Library/Ruby/Site/2.6.0/rubygems/commands/install_command.rb:169:in `execute'
	/Library/Ruby/Site/2.6.0/rubygems/command.rb:327:in `invoke_with_build_args'
	/Library/Ruby/Site/2.6.0/rubygems/command_manager.rb:252:in `invoke_command'
	/Library/Ruby/Site/2.6.0/rubygems/command_manager.rb:192:in `process_args'
	/Library/Ruby/Site/2.6.0/rubygems/command_manager.rb:150:in `run'
	/Library/Ruby/Site/2.6.0/rubygems/gem_runner.rb:51:in `run'
	/usr/bin/gem:21:in `<main>'

**Additional context**
Add any other context about the issue here.

**Comment by bitlevi** [comment]
@jcbelair Pinging you in case you missed the above comment. Don't hesitate to reach out if you need any help. Happy Sunday!

**Comment by jcbelair** [comment]
still issues.. this is where i am

************************
Installed ruby-3.2.2 to /Users/jcb/.rbenv/versions/3.2.2


NOTE: to activate this Ruby version as the new default, run: rbenv global 3.2.2
jcb@jcs-MacBook-Pro ~ % rbenv global 3.2.2
jcb@jcs-MacBook-Pro ~ % gem install jekyll bundler
ERROR:  While executing gem ... (Errno::EACCES)
    Permission denied @ dir_s_mkdir - /Users/jcb/.local/share/gem/specs
	/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:239:in `mkdir'
	/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:239:in `fu_mkdir'
	/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:217:in `block (2 levels) in mkdir_p'
	/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:215:in `reverse_each'
	/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:215:in `block in mkdir_p'
	/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:200:in `each'
	/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:200:in `mkdir_p'
	/Library/Ruby/Site/2.6.0/rubygems/source.rb:151:in `fetch_spec'
	/Library/Ruby/Site/2.6.0/rubygems/resolver/api_specification.rb:92:in `spec'
	/Library/Ruby/Site/2.6.0/rubygems/resolver/installer_set.rb:98:in `add_always_install'
	/Library/Ruby/Site/2.6.0/rubygems/dependency_installer.rb:322:in `resolve_dependencies'
	/Library/Ruby/Site/2.6.0/rubygems/commands/install_command.rb:205:in `install_gem'
	/Library/Ruby/Site/2.6.0/rubygems/commands/install_command.rb:230:in `block in install_gems'
	/Library/Ruby/Site/2.6.0/rubygems/commands/install_command.rb:223:in `each'
	/Library/Ruby/Site/2.6.0/rubygems/commands/install_command.rb:223:in `install_gems'
	/Library/Ruby/Site/2.6.0/rubygems/commands/install_command.rb:169:in `execute'
	/Library/Ruby/Site/2.6.0/rubygems/command.rb:327:in `invoke_with_build_args'
	/Library/Ruby/Site/2.6.0/rubygems/command_manager.rb:252:in `invoke_command'
	/Library/Ruby/Site/2.6.0/rubygems/command_manager.rb:192:in `process_args'
	/Library/Ruby/Site/2.6.0/rubygems/command_manager.rb:150:in `run'
	/Library/Ruby/Site/2.6.0/rubygems/gem_runner.rb:51:in `run'
	/usr/bin/gem:21:in `<main>'



*************************

**Comment by bitlevi** [comment]
Hey @jcbelair, on line 5 instead of running `gem install jekyll bundler` run `sudo gem install jekyll bundler`

**Comment by BitcoinQnA** [comment]
@bitlevi thank you for your input here.

@jcbelair any response to BL's latest comments? I'd like to get this issue resolved.
