### ISSUE TITLE
Search function varies from page to page

### ISSUE THREAD

**Issue by bitlevi** [BitcoinQnA/Bitcoiner.Guide#25]
**I am creating this issue as a challenge more than an actual issue of bitcoiner.guide. IMO, this issue falls into the enhancement category.**

**Describe the issue**
If you use the search function on the home page and search for "RoboSats" nothing comes up (first screenshot). If you navigate to "Articles" and then search for "RoboSats" the article comes up (second screenshot). As a user, I want to be able to search the entire website thoroughly.

<img width="1552" alt="Screenshot 2023-06-07 at 16 39 57 2" src="https://github.com/BitcoinQnA/Bitcoiner.Guide/assets/130449519/6b67277c-bf57-43b4-8069-71f05a80b272">

<img width="1552" alt="Screenshot 2023-06-07 at 16 40 23" src="https://github.com/BitcoinQnA/Bitcoiner.Guide/assets/130449519/8fff02ec-2a90-4d8b-989a-be45cdfc1735">

Surprisingly, if you run bitcoiner.guide on your machine and search "RoboSats" on the home page, it actually comes up! (third screenshot)

<img width="1552" alt="Screenshot 2023-06-07 at 16 42 50" src="https://github.com/BitcoinQnA/Bitcoiner.Guide/assets/130449519/074f2418-1cc6-48d5-8249-b4a15648e536">

**Additional context**
From my limited understanding, the logic involved in the search function of Jekyll can be found in `_includes` > `search.html`

I wonder if this is a limitation of Jekyll's search library or if the code can be modified to account for objects inside and outside their folders to enhance the search function. **However, it works on the local version, so there is something weird about the online version.**

Additionally, it seems that the *backward* search works. Let me explain, if you are on "RoboSats" and search for "Articles", the page comes up. 

If you have already explored this issue @BitcoinQnA, I am curious to know more about it 👀

**Comment by BitcoinQnA** [comment]
This is interesting, I actually hadn't noticed it. My first idea would be to search through the 'beautiful Jekyll' repo issues to see if anyone's mentioned such a thing before.

**Comment by bitlevi** [comment]
Came back to this issue and it resolved itself for some unknown reasons. I cannot replicate the issue lol! Closing the ticket.

<img width="1440" alt="Screenshot 2023-08-23 at 08 51 10" src="https://github.com/BitcoinQnA/Bitcoiner.Guide/assets/130449519/77576cf1-2eaa-4333-8167-f2a61efdd680">

**Comment by BitcoinQnA** [comment]
Awesome! Thanks for closing the loop here.
